server:
  port: 8808
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'

springdoc:
  version: 3.1
  api-docs:
    version: openapi_3_1
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: ASC
    operationsSorter: none # method(default) path alpha none
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: Auth
      paths-to-match: /signIn, /signOut, /signUp
    - group: Business
      paths-to-match: /biz
    - group: System
      paths-to-match: /user/**
  cache:
    disabled: true

############################# spring common config end ###############################

spring:
  application:
    name: kai
  profiles:
    default: dev
  output:
    ansi:
      enabled: always
  cloud:
    config:
      enabled: false
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 5000
logging:
  file:
    name: logs/${spring.application.name}.log

############################# spring boot starter config end ###############################

shiro:
  crypto:
    hash-algorithm: SHA-256
    hash-iterations: 3
    system-salt: kaiSecretKey
  loginUrl: /signIn
  # Let Shiro Manage the sessions
  userNativeSessionManager: true
  # disable URL session rewriting
  sessionManager:
    sessionIdUrlRewritingEnabled: false
  anon:
    - /hello
    - /signUp,/signIn,/signOut
    - /static/**,/templates/**
    - /error
    - /swagger-ui/**,/swagger-resources/**,/v3/api-docs/**
    - /user/**

############################# shiro config end ###############################

mybatis-plus:
  type-enums-package: com.travelwink.kai.framework.enums