server:
  port: 8808
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'

springdoc:
  version: 3.1
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: Framework
      paths-to-match: /login
    - group: System
      paths-to-match: /user/**
    - group: Business
      paths-to-match: /biz
  cache:
    disabled: true

############################# spring common config end ###############################
shiro:
  crypto:
    hash-algorithm: SHA-256
    hash-iterations: 3
  loginUrl: /login
  # Let Shiro Manage the sessions
  userNativeSessionManager: true
  # disable URL session rewriting
  sessionManager:
    sessionIdUrlRewritingEnabled: false
  anon:
    - /hello
    - /login,/logout
    - /static/**,/templates/**
    - /error
    - /swagger-ui/**,/swagger-resources/**,/v3/api-docs/**
    - /user/**


spring:
  application:
    name: kai
  profiles:
    default: dev
  output:
    ansi:
      enabled: always
  cloud:
    config:
      enabled: false
logging:
  file:
    name: logs/${spring.application.name}.log